package com.mohamed.cinema;

import java.util.List; 

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class CinemaController {
	
	@Autowired 	// This means to get the bean called userRepository, Which is auto-generated by Spring, we will use it to handle the data
	private CinemaService cinemaService;
	
	@RequestMapping("/cinemas")
	public List<Cinema> getCinemas(){
		return cinemaService.getCinemas();
	}
	
	@RequestMapping("/cinemas/{id}")
	public Cinema getCinema(@PathVariable Integer id) {
		return cinemaService.getCinema(id);
	}
	
	@RequestMapping(method=RequestMethod.POST, value="/cinemas")
	public void addCinema(@RequestBody Cinema cinema) {
		cinemaService.addCinema(cinema);
	}
	
	@RequestMapping(method=RequestMethod.DELETE, value="/cinemas/{id}")
	public void deleteCinema(@PathVariable Integer id) {
		cinemaService.deleteCinema(id);
	}
	
	@RequestMapping(method=RequestMethod.PUT, value="/cinemas/{id}")
	public void updateCinema(@PathVariable Integer id, @RequestBody Cinema cinema) {
		cinemaService.updateCinema(id, cinema);
	}

}
